modules:
  http_2xx:
    prober: http
    timeout: 0.5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: []
      method: GET
      preferred_ip_protocol: "ip4"

  https_2xx:
    prober: http
    timeout: 0.5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: []
      method: GET
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4"

  icmp:
    prober: icmp
    timeout: 0.5s
    icmp:
      preferred_ip_protocol: "ip4"

  tcp_connect:
    prober: tcp
    timeout: 0.5s
    tcp:
      preferred_ip_protocol: "ip4"